### PR TITLE
Update to PureScript v0.15.0

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Backlinking to purescript/purescript#4244

Migrates FFI to ES modules

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
:ping_pong: @thomashoneyman

**Comment by thomashoneyman** [comment]
I don’t know how to fix this test. JSDOM seems to have issues with XPath (from reading through their bug tracker). Maybe we disable it for now and open an issue unless perhaps @bbarker knows what’s going wrong

**Comment by JordanMartinez** [comment]
This issue happened last time we were updating things for `v0.14.0`. I can't recall how we resolved it then, but we may have just merged it.

**Comment by thomashoneyman** [comment]
JSDOM was introduced to help with that:
https://github.com/purescript-web/purescript-web-dom-xpath/pull/6/commits/ada7d6e11e622fc740a67d6fdd6ae41806b6bf08

Personally I don’t feel like it’s a good use of time to try and fix this unless it’s quick and direct. I’d rather wrap around if we have time. We can disable tests in the meantime

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
